Add plugin documentation
mathildebrosseau/transition_qgis pull request #46
Opened 2024-04-09 19:08 UTC by manelkdm

2024-04-10 15:22 UTC, mathildebrosseau requested changes

2024-04-10 15:22 UTC, mathildebrosseau commented on README.md
> +The prompt also asks users for the server URL that is to be used. By default, it is set to `http://localhost:8080` but can be edited by users. The login gets an authentication token from the Transiti
```suggestion
Users also have to provide the URL to the Transition server URL to be used. The default value is `http://localhost:8080`, but can it be edited. 

The login process retrieves an authentication token from the Transition application. When the token expires, the user will be prompted to login again to obtain a new one.
```

2024-04-10 15:22 UTC, mathildebrosseau commented on README.md
> +After a successful login, users have access to the plugin, which is a dockwidget.\
```suggestion
After a successful login, the plugin appears as a dockwidget.\
```

2024-04-10 15:22 UTC, mathildebrosseau commented on README.md
> +The dockwidget contains multiple tabs which are described in the following.
```suggestion
The dockwidget features multiple tabs, each of which is outlined below.
```

2024-04-10 15:22 UTC, mathildebrosseau commented on README.md
> +For transit, if the **Calculate with alternatives** option is checked, multiple alternatives can be returned. When that is the case, the alternative routes will be displayed in a sub-group.
Ajouter l'explication et la photo pour le Route name

2024-04-10 15:22 UTC, mathildebrosseau commented on README.md
> +For transit, if the **Calculate with alternatives** option is checked, multiple alternatives can be returned. When that is the case, the alternative routes will be displayed in a sub-group.
Expliquer que les résultats se font écraser quand on redemande une route sans spécifier le nom

2024-04-10 15:22 UTC, mathildebrosseau commented on README.md
> +If the **Separate polygons into different layers** option is checked, the result will be a group layer containing a separate layer for each polygon. Otherwise, the result will just be one layer conta
Ajouter l'explication et la photo pour le Accessibility map name + Expliquer que les résultats se font écraser quand on redemande une route sans spécifier le nom

2024-04-10 15:22 UTC, mathildebrosseau commented on README.md
> +The page also allows users to disconnect from the plugin.
```suggestion
The page also allows users to log out from the plugin.  
```

2024-04-10 15:22 UTC, mathildebrosseau commented on README.md
> +To contribute to the Transition QGIS plugin, you can clone this reponsitory in `~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/`. The plugin should then be added to your installed plugins
Non il faut que l'utilisateur fasse qqch dans le plugin manager pour que le plugin s'affiche une fois que le dossier est cloné messemble

2024-04-10 15:22 UTC, mathildebrosseau commented on README.md
> +When new code is added, the fileds that are going to be displayed in the QGIS UI need to be translated to french. In order to allow that, you first need to install QT Linguist.
```suggestion
When new code is added, the fields that are going to be displayed in the QGIS UI need to be translated to french. In order to allow that, you first need to install QT Linguist.
```

2024-04-10 15:22 UTC, mathildebrosseau commented on README.md
> +The fields that are to be translated need to be wrapped in a `self.tr` clause. For example :
```suggestion
All text visible by the user needs to be translated. To allow this, they need to be wrapped in a `self.tr` clause. For example :
```

2024-04-10 15:22 UTC, mathildebrosseau commented on README.md
> +After that, you can open the `transition_qgis_fr.ts` file in QT Linguist and write the translation of each field. Finally, once that is done, you need to run the following command in the `i18n` direc
```suggestion
After that, you can open the `transition_qgis_fr.ts` file in QT Linguist, write the translation of each field and save your changes. Once that is done, run the following command in the `i18n` directory :
```

2024-04-10 15:22 UTC, mathildebrosseau commented on create_accessibility.py
> +
enlever, deja là

2024-04-10 15:22 UTC, mathildebrosseau commented on create_login.py
> +from transition_lib import Transition
mauvais import, retirer ce changement

2024-04-10 15:22 UTC, mathildebrosseau commented on create_route.py
> +
enlever, ce changement est déjà là d'une autre PR

2024-04-10 15:22 UTC, mathildebrosseau commented on create_route.py
> +                                [self.modeChoice, self.radioButtonsWidget, self.departureOrArrivalTime, self.withAlternativeChoice, self.scenarioChoice, self.routeName, self.maxParcoursTimeChoice, se
pourquoi ce changement ? je pense faudrait l'enlever

2024-04-10 15:22 UTC, mathildebrosseau commented on README.md
> +![alt text](docs/screenshots/plugin_icons.png)
ajouter cette tite image là au début aussi quand on explique comment ajouter le plugin!

2024-04-10 15:22 UTC, mathildebrosseau commented on requirements.txt
> +transition-lib==0.1.11
pyTransition

2024-04-10 15:22 UTC, mathildebrosseau commented on transition_qgis.py
> +                coord_latitude=self.selectedCoords['accessibilityMapPoint'].y(),
enlever ce changement

2024-04-10 15:22 UTC, mathildebrosseau commented on README.md
> +Install `Transition` through the QGIS plugin manager.
avec une photo aussi peut-être ?

2024-04-10 17:05 UTC, manelkdm commented on README.md
> +The prompt also asks users for the server URL that is to be used. By default, it is set to `http://localhost:8080` but can be edited by users. The login gets an authentication token from the Transiti
"Users also have to provide the URL to the Transition server URL to be used"
je pense que la fin de la phrase est pas vraiment bonne ?

2024-04-10 17:06 UTC, manelkdm commented on README.md
> +To contribute to the Transition QGIS plugin, you can clone this reponsitory in `~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/`. The plugin should then be added to your installed plugins
je pense pas, de mémoire c'était juste une ligne de code que tu avais ajouté pour le voir puis elle est déjà pushed

2024-04-10 17:08 UTC, mathildebrosseau commented on README.md
> +The prompt also asks users for the server URL that is to be used. By default, it is set to `http://localhost:8080` but can be edited by users. The login gets an authentication token from the Transiti
au pire on enlève le "to be used" ? je pense ça se dit bien quand même

2024-04-10 17:09 UTC, mathildebrosseau commented on README.md
> +To contribute to the Transition QGIS plugin, you can clone this reponsitory in `~/.local/share/QGIS/QGIS3/profiles/default/python/plugins/`. The plugin should then be added to your installed plugins
faudrait retourner voir nos tutoriels lol

2024-04-11 19:47 UTC, mathildebrosseau approved these changes

2024-04-11 19:47 UTC, mathildebrosseau commented on requirements.txt
> +pytransition==0.1.11
c'est 0.0.1 maintenant que c'est pyTransition

2024-04-11 19:48 UTC, merged